language: node_js
node_js:
    - "12"
    - "13"

os:
    - osx

install:
    - npm install -g npm@latest
    - npm install

script:
    - npm run test:ci:coverage

after_script:
    - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
